openapi: 3.1.0
info:
  title: MTHMR CashBack
  version: 0.1.0
servers:
  - url: https://stgapi-cashback.mthmr.com
paths:
  /gettoken:
    get:
      tags:
        - Authentication
      summary: Get Token
      description: |-
        Use this endpoint to obtain an authentication token for accessing other endpoints.
      operationId: get-token
      parameters:
        - name: APPLICATION-ID
          in: header
          required: true
          description: The application ID issued when connecting to the application.
          schema:
            type: string
            title: Application-Id
        - name: APPLICATION-KEY
          in: header
          required: true
          description: The application key issued when connecting to the application.
          schema:
            type: string
            title: Application-Key
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTokenResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /customers/:
    post:
      tags:
        - Customer
      summary: Add Customers
      description: |-
        Use this endpoint to create new customer records in MTHMR CashBack, allowing you to add one or more customer objects to the system.
      operationId: add-customers
      parameters:
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomerBase'
              title: Customerd
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/PostCustomerResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
        - Customer
      summary: Get Customers
      description: This endpoint allows you to retrieve a list of all your registered customers.
      operationId: get-customers
      parameters:
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerListResponse'
              example:
                - customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d2"
                  birthday: "1995-03-15"
                  gender: Female
                - customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d67"
                  birthday: "1990-12-01"
                  gender: Male
                - customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d234"
                  birthday: "1984-07-22"
                  gender: Female
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /cashbackpayments:
    get:
      tags:
        - Customer
      summary: Get Cashback Payments
      description: |-
        This endpoint is designed to retrieve detailed information about cashback payments that have been made within a specific date range. By specifying the start and end dates, you can easily access accurate payment data.
      operationId: get-cashback-payments
      parameters:
        - name: date_from
          in: query
          required: false
          description: The start date for the date range you want to filter cashback payments.
          schema:
            type: string
            format: date
            title: Date From
            example: YYYY-MM-DD
        - name: date_to
          in: query
          required: false
          description: The end date for the date range you want to filter cashback payments.
          schema:
            type: string
            format: date
            title: Date To
            example: YYYY-MM-DD
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CashbackPaymentsListResponse'
              example:
                - date: "2024-03-11"
                  customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272"
                  offer_id: 203
                  sum: 33.0
                  count: 1
                - date: "2024-03-26"
                  customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272"
                  offer_id: 203
                  sum: 49.5
                  count: 1
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /transactions:
    post:
      tags:
        - Transaction
      summary: Add Multiple Transactions
      description: |-
        This endpoint enables the addition of multiple transaction records to the system. It is ideal for adding a large number of transactions at once, saving time and effort.
      operationId: add-transactions
      parameters:
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TransBase'
              title: Transactiond
            example:
              - transaction_id: "b65cca2a-6809-11ee-8c99-0242ac1200169"
                description: description
                customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272"
                date: "2024-02-25T10:27:03.987662"
                merchant_name: MTHMR
                location:
                  city: Riyadh
                  country: Saudi Arabia
                amount: 100
              - transaction_id: "b65cca2a-6809-11ee-8c99-0242ac12000322790"
                description: description
                customer_id: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272"
                date: "2024-03-11T10:27:03.987662"
                merchant_name: MTHMR
                location:
                  city: Riyadh
                  country: Saudi Arabia
                amount: 150
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionsResponse'
              example:
                  - event_id: fc56d1b3-68d5-45f2-bce9-0c433c9af20a
                    payments:
                  - transaction_id: b65cca2a-6809-11ee-8c99-0242ac1200169
                    cashback: 33.0
                    payment_date: '2024-03-11T10:27:03.987662'
                  - transaction_id: b65cca2a-6809-11ee-8c99-0242ac12000322790
                    cashback: 49.5
                    payment_date: '2024-03-26T10:27:03.987662'
              errors: []
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /transactions-history:
    post:
      tags:
        - Transaction
      summary: Add Transactions History
      description: |-
        This endpoint allows you to add historical transaction data for that particular customer. This data can be later used to qualify the customer for offers that better suit him
      operationId: add-transactions-history
      parameters:
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TransBase'
              title: Transactiond
            example:
              - transaction_id: a55cca2a-6809-11ee-8c99-0242ac1200551
                description: description
                customer_id: a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272
                date: "2024-02-25T10:27:03.987662"
                merchant_name: MTHMR
                location:
                  city: Riyadh
                  country: Saudi Arabia
                amount": 100
              - transaction_id: e65cca2a-6809-11ee-8c99-0242ac120005531
                description: description
                customer_id: a8de52aa-49e7-4e5c-bb66-1c82ac1d551d272
                date: "2024-03-11T10:27:03.987662"
                merchant_name: MTHMR
                location:
                  city: Riyadh
                  country: Saudi Arabia
                amount": 150
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionsHistoryResponse'
              example:
                payments:
                  - transaction_id: a55cca2a-6809-11ee-8c99-0242ac1200551
                    cashback: 0
                  - transaction_id: e65cca2a-6809-11ee-8c99-0242ac120005531
                    cashback: 0
              errors: []
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /activeoffers:
    get:
      tags:
        - Offer
      summary: Get All Active Offers
      description: This endpoint retrieves all active offers currently available in the system and returns a formatted list. 
      operationId: get-all-offers
      parameters:
        - name: Token
          in: header
          required: false
          description: The authentication token for accessing the API.
          schema:
            type: string
            example: 'Bearer <YOUR_TOKEN>'
            title: Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOfferResponse'
              example:
                - id: 202
                  name: Max3
                  merchant_name: ALAM Supermarket
                  merchant_logo: "https://api.lunedata.io/media/brand/alam_1.png"
                  warranty: 15
                  discount: 312
                  valid_from: "2024-01-29T00:00:00"
                  valid_to: "2025-02-28T00:00:00"
                - id: 203
                  name: New one
                  merchant_name: MTHMR
                  merchant_logo: "https://api.lunedata.io/media/brand/AE356093-th.png"
                  warranty: 15
                  discount: 33
                  valid_from: "2024-01-22T00:00:00"
                  valid_to: "2024-04-18T00:00:00"
                - id: 215
                  name: Okay offer
                  merchant_name: OkayNewMaxBrand
                  merchant_logo: "https://api.lunedata.io/media/brand/Screenshot2023-07-10at11.22.18.png"
                  warranty: 15
                  discount: 20
                  valid_from: "2024-01-01T00:00:00"
                  valid_to: "2024-12-31T00:00:00"
        '404':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError404'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GetTokenResponse:
      type: object
      properties:
        Token:
          type: string
          description: The token  used to authenticate a user with the API.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTE2NTU2NDgsImlhdCA3MTcxMTY0OTY0OCwic3ViIjoibFFSUE2frtk5dG5HVnhYYmc0VHMifQ.W5SVuoeUI5PMBBcIJjBiaTVy1Snn1u61FeF291mQD7o
    PostCustomerResponse:
      type: string
      description: A message indicating the number of customers added and updated.
      example: "Customers: added 1, updated 0"
    CustomerResponseObject:
      type: object
      properties:
        customer_id:
          type: string
          description: The unique identifier for the customer.
          example: a8de52aa-49e7-4e5c-bb66-1c82ac1d551d67
        birthday:
          type: string
          format: date
          description: The birthday of the customer.
          example: 1995-03-15
        gender:
          type: string
          description: The gender of the customer.
          enum: [Male, Female]
          example: Male
    CustomerListResponse:
      description: An array of objects with the customers.
      type: array
      items:
        $ref: '#/components/schemas/CustomerResponseObject'
    CashbackPaymentsResponseObject:
      type: object
      properties:
        date:
          type: string
          format: date
          description: The date of the cashback payment.
          example: "2023-10-26"
        customer_id:
          type: string
          description: The unique identifier for the customer.
          example: "a8de52aa-49e7-4e5c-bb66-1c82ac1d551d234"
        offer_id:
          type: integer
          description: The identifier of the offer associated with the cashback payment.
          example: 203
        sum:
          type: number
          format: float
          description: The total amount of the cashback payment.
          example: 330.0
        count:
          type: integer
          description: The number of transactions for this specific date, offer, and client.
          example: 10
    CashbackPaymentsListResponse:
      type: array
      items:
        $ref: '#/components/schemas/CashbackPaymentsResponseObject'
    CreateTransactionsResponse:
      type: object
      properties:
        event_id: 
          type: string
          description: Token to be used in your webhooks
        payments:
          type: array
          description: List of created transactions
          items:
            type: object
            properties:
              transaction_id:
                type: string
                description: The ID of the transaction
              cashback:
                type: number
                description: The cashback amount for the transaction
              payment_date:
                type: string
                format: date-time
                description: The date and time of the payment
        errors:
          type: array
          description: List of errors, if any
          items:
            type: string
            description: Description of the error
    CreateTransactionsHistoryResponse:
      type: object
      properties:
        payments:
          type: array
          description: List of created transactions
          items:
            type: object
            properties:
              transaction_id:
                type: string
                description: The ID of the transaction
              cashback:
                type: number
                description: The cashback amount for the transaction
        errors:
          type: array
          description: List of errors, if any
          items:
            type: string
            description: Description of the error
    GetOfferResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            description: The unique identifier of the offer.
          name:
            type: string
            description: The name of the offer.
          merchant_name:
            type: string
            description: The name of the merchant.
          merchant_logo:
            type: string
            format: uri
            description: URL of the merchant's logo.
          warranty:
            type: integer
            description: Refers to the days the payout is delayed, as customers can return the purchase until the warranty lasts.
          discount:
            type: number
            description: The discount percentage of the offer.
          valid_from:
            type: string
            format: date-time
            description: Start date of the offer validity.
          valid_to:
            type: string
            format: date-time
            description: End date of the offer validity.
    CustomerBase:
      properties:
        customer_id:
          type: string
          title: Customer Id
          description: A unique identifier for the customer.
          example: a8de52aa-49e7-4e5c-bb66-1c82ac1d551d
        birthday:
          type: string
          format: date
          title: Birthday
          description: The birthdate of the customer.
          example: YYYY-MM-DD
        gender:
          type: string
          title: Gender
          description: The gender of the customer.
          example: Male
        location:
          $ref: '#/components/schemas/LocationBase'
      type: object
      required:
        - birthday
        - customer_id
        - gender
        - location
      title: CustomerBase
    NotFoundError404:
      type: object
      properties:
        detail:
          type: string
          description: Error message indicating that resource was not found.
          example: Not Found
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
              msg:
                type: string
              type:
                type: string
      required:
        - detail
    TransBase:
      properties:
        transaction_id:
          type: string
          title: Transaction Id
          description: The unique identifier for the transaction.
          example: b65cca2a-6809-11ee-8c99-0242ac120002
        description:
          type: string
          title: Description
          description: A brief description or note about the transaction.
          example: This is a brief note about the transaction.
        customer_id:
          type: string
          title: Customer Id
          description: The unique identifier for the customer associated with the transaction.
          example: a8de52aa-49e7-4e5c-bb66-1c82ac1d
        date:
          type: string
          format: date-time
          title: Date
          description: The date and time when the transaction was made.
          example: '2024-04-17T13:45:00Z'
        amount:
          type: number
          title: Amount
          description: The monetary value of the transaction.
          example: 150
        merchant_name:
          type: string
          title: Merchant Name
          description: The name of the merchant where the transaction occurred.
          example: MTHMR
        location:
          $ref: '#/components/schemas/LocationBase'
    LocationBase:
      type: object
      title: Location
      description: An object containing details about the customer's location.
      properties:
        country:
          type: string
          title: Country
          description: The country where the customer resides.
          example: Saudi Arabia
        city:
          type: string
          title: City
          description: The city where the customer resides.
          example: Riyadh
      required:
        - country
        - city
